### ISSUE TITLE
Server crash upon outdated client join

### ISSUE THREAD

**Issue by LimeTheOn** [LatvianModder/FTBUtilities#146]
Friend tried to join our server with an outdated client and:
Time: 26/06/16 20:26
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.feed_the_beast.ftbl.FTBLibEventHandler.onPlayerLoggedOut(FTBLibEventHandler.java:105)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_220_FTBLibEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:563)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:379)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:806)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/23

**Comment by LatvianModder** [comment]
Fixed in pre2
