### ISSUE TITLE
[1.10.2] 3.x Chunkloading crash w/ huge map corruption

### ISSUE THREAD

**Issue by gdude2002** [LatvianModder/FTBUtilities#229]
Here's a crash log. Seems to have been caused by a user logging on. Prompt fix would be incredibly helpful.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.321.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.51.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  IC2core (industrialcraft-2-2.6.85-ex110.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.56.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/11/16 6:40 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:228)
    at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:807)
    at com.feed_the_beast.ftbu.api_impl.LoadedChunkStorage.checkChunk(LoadedChunkStorage.java:107)
    at com.feed_the_beast.ftbu.api_impl.LoadedChunkStorage.checkAll(LoadedChunkStorage.java:73)
    at com.feed_the_beast.ftbu.world.FTBUUniverseData.func_73660_a(FTBUUniverseData.java:457)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.feed_the_beast.ftbl.api_impl.FTBLibAPI_Impl.func_73660_a(FTBLibAPI_Impl.java:184)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:739)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1150965224 bytes (1097 MB) / 4082106368 bytes (3893 MB) up to 11453595648 bytes (10923 MB)
    JVM Flags: 1 total; -Xmx12288M
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
    FML: MCP 9.32 Powered by Forge 12.18.1.2092 69 mods loaded, 69 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
    UCHIJAAAA   Forge{12.18.1.2092} [Minecraft Forge] (minecraft_server.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJAAAA   actuallyadditions{1.10.2-r65} [Actually Additions] (ActuallyAdditions-1.10.2-r65.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
    UCHIJAAAA   immersiveengineering{0.10-44} [Immersive Engineering] (ImmersiveEngineering-0.10-44.jar) 
    UCHIJAAAA   JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
    UCHIJAAAA   AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
    UCHIJAAAA   Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4e.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2087} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2087-universal.jar) 
    UCHIJAAAA   bookshelf{1.4.1.321} [Bookshelf] (Bookshelf-1.10.2-1.4.1.321.jar) 
    UCHIJAAAA   bookshelfapi{3.2.2} [Bookshelf] (Bookshelf-API-1.10.2-3.2.2.jar) 
    UCHIJAAAA   Botania{r1.9-328} [Botania] (Botania r1.9-328.jar) 
    UCHIJAAAA   BuildersGuides{1.10.2-1.0.2} [Builder's Guides] (buildersguides-1.10.2-1.0.2.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.51} [Chisel] (Chisel-MC1.9.4-0.0.6.51.jar) 
    UCHIJAAAA   mcmultipart{1.3.0_83} [MCMultiPart] (MCMultiPart-experimental-1.3.0_83-universal.jar) 
    UCHIJAAAA   chiselsandbits{12.4} [Chisels & Bits] (chiselsandbits-12.4.jar) 
    UCHIJAAAA   cookingforblockheads{4.2.16} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.16.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   darkutils{1.1.4.86} [Dark Utilities] (DarkUtilities-1.10.2-1.1.4.86.jar) 
    UCHIJAAAA   shadowmc{3.4.4} [ShadowMC] (ShadowMC-1.10.2-3.4.4.jar) 
    UCHIJAAAA   DiscordChat{1.4.0} [DiscordChat] (DiscordChat-1.10.2-1.4.0.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0b.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
    UCHIJAAAA   IC2{2.6.85-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.85-ex110.jar) 
    UCHIJAAAA   forestry{5.2.14.270} [Forestry] (forestry_1.10.2-5.2.14.270.jar) 
    UCHIJAAAA   ftbl{3.0.0} [FTBLib] (FTBLib-1.10.2-3.0.0.4.jar) 
    UCHIJAAAA   ftbu{3.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.0.0.3.jar) 
    UCHIJAAAA   graves{1.10.2-b28-universal} [Graves Mod] (Graves-1.10.2-b28-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
    UCHIJAAAA   JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.3.0b1} [JourneyMap] (journeymap-1.10.2-5.3.0b1-unlimited.jar) 
    UCHIJAAAA   malisiscore{1.10.2-4.2.5} [MalisisCore] (malisiscore-1.10.2-4.2.5.jar) 
    UCHIJAAAA   malisisdoors{1.10.2-5.1.3} [MalisisDoors] (malisisdoors-1.10.2-5.1.3.jar) 
    UCHIJAAAA   Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    UCHIJAAAA   fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
    UCHIJAAAA   progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJAAAA   randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
    UCHIJAAAA   reborncore{2.7.1.38} [RebornCore] (RebornCore-1.10.2-2.7.1.38-universal.jar) 
    UCHIJAAAA   reborncore-mcmultipart{2.7.1.38} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.1.38-universal.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   refinedstorage{1.1.3} [Refined Storage] (refinedstorage-1.1.3.jar) 
    UCHIJAAAA   rftools{5.51} [RFTools] (rftools-1.10-5.51.jar) 
    UCHIJAAAA   rftoolscontrol{1.3.4} [RFTools Control] (rftoolsctrl-1.10-1.3.4.jar) 
    UCHIJAAAA   SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
    UCHIJAAAA   substratum{1.8.1.0} [Substratum] (Substratum-1.10.2-1.8.1.0.jar) 
    UCHIJAAAA   thutcore{3.6.5} [ThutCore] (thutcore-1.9.4-3.6.5.1.jar) 
    UCHIJAAAA   thuttech{4.0.5} [Thut's Tech] (thuttech-4.0.5.jar) 
    UCHIJAAAA   TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
    UCHIJAAAA   icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
    UCHIJAAAA   wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
    UCHIJAAAA   fluidity{6.1.1} [Fluidity] (Fluidity-6.1.1.jar) 
    UCHIJAAAA   UniDict{1.10.2-1.8c} [UniDict] (UniDict-1.10.2-1.8c.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.321.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
MalisisCorePlugin (malisiscore-1.10.2-4.2.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.51.jar)
  team.chisel.common.asm.ChiselTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.85-ex110.jar)

LoadingHook (Mekanism-1.10.2-9.2.1.56.jar)

    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

    EnderIO: No known problems detected.
    Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/Mekanism-1.10.2-9.2.1.56.jar!/cofh/api/energy/TileEnergyHandler.class
    Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

    Profiler Position: N/A (disabled)
    Player Count: 6 / 30; [EntityPlayerMP['arbot'/1148, l='world', x=898.69, y=65.00, z=-567.98], EntityPlayerMP['alieu'/681564, l='world', x=-62.78, y=63.00, z=105.11], EntityPlayerMP['rrracheljoy'/649014, l='world', x=895.51, y=63.00, z=-585.60], EntityPlayerMP['ZaydSophos'/983385, l='world', x=774.87, y=77.61, z=-728.07], EntityPlayerMP['Spacegatr'/597951, l='world', x=462.50, y=91.01, z=-622.50], EntityPlayerMP['IOTaigaFox'/995021, l='world', x=438.05, y=85.00, z=-1402.37]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by utoc** [comment]
Also seeing this crash: http://pastebin.com/EUbBt8Xg

It happens when one particular user logs in: server crash every time.  I have three separate crashes from him until I asked him to stop using FTBUtil for chunkloading until the next release.

Running FTBLib-1.10.2-3.1.1, FTBUtilities-1.10.2-3.1.1 on FML 2109

**Comment by gdude2002** [comment]
Because of another issue I ended up compiling my own builds of ftblib and ftbu. I disabled chunkloading via the ftbu config, and while it doesn't actually disable chunkloading, I haven't had a problem since.

**Comment by MCTyler** [comment]
If you don't mind...can you tell us where to insert the dependencies to build the mod please. When I try to build I get a forbidden error for ftblib. I created a libs folder and put the jar in there but it wouldn't work. I run the build command line in Linux ./gradlew build.

**Comment by gdude2002** [comment]
That's all you need. Check the file permissions.

**Comment by MCTyler** [comment]
I just downloaded the zip of the file repository...don't really understand how file permissions would effect it but I'll check.

**Comment by gdude2002** [comment]
Oh, I see. That's a different issue. 

Perhaps check the Mojang system status and try again later - sounds like they broke it

**Comment by Watchful1** [comment]
I am having the same problem.

http://pastebin.com/DKA9jDDS

**Comment by frenzye** [comment]
I get this same crash when I try to mess with default_rank_config.json and FTBU just ignores ranks.json if I create it 

http://pastebin.com/AMdTKwy0

**Comment by gdude2002** [comment]
Your crash happens at a different state of execution; you probably want to make a new issue for it

**Comment by LatvianModder** [comment]
Outdated FTBU/L version, update it and see if you can reproduce the crash
