### ISSUE TITLE
[1.10.2] Crash on loading

### ISSUE THREAD

**Issue by xSparky911x** [LatvianModder/FTBUtilities#264]
Using 
forge-12.18.2.2118
FTBUtilities-1.10.2-3.1.4.jar
FTBLib-1.10.2-3.1.4.jar

Same result with
forge-12.18.2.2118
FTBUtilities-1.10.2-3.1.3.jar
FTBLib-1.10.2-3.1.3.jar

Works with
forge-12.18.2.2118
FTBUtilities-1.10.2-3.1.2.jar
FTBLib-1.10.2-3.1.2.jar

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.229.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/11/16 3:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/context/IContext
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:617)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/context/IContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.feed_the_beast.ftbl.lib.AsmData.getClass(AsmData.java:78)
	at com.feed_the_beast.ftbl.lib.AsmData.findAnnotatedObjects(AsmData.java:108)
	at com.feed_the_beast.ftbl.lib.AsmData.findRegistryObjects(AsmData.java:224)
	at com.feed_the_beast.ftbl.api_impl.FTBLibRegistries.init(FTBLibRegistries.java:81)
	at com.feed_the_beast.ftbl.api_impl.FTBLibAPI_Impl.init(FTBLibAPI_Impl.java:53)
	at com.feed_the_beast.ftbl.FTBLibMod.onPreInit(FTBLibMod.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.server.permission.context.IContext
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 472668648 bytes (450 MB) / 2515533824 bytes (2399 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2118 86 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2118.jar) 
	UCH	Forge{12.18.2.2118} [Minecraft Forge] (forge-1.10.2-12.18.2.2118.jar) 
	UCH	JEI{3.13.2.362} [Just Enough Items] (jei_1.10.2-3.13.2.362.jar) 
	UCH	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCH	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCH	BetterAchievements{0.3.2.35} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.35.jar) 
	UCH	bettertitlescreen{1.2e} [Better Title Screen] (BetterTitleScreen-1.10.2-1.2e.jar) 
	UCH	BiomeTweaker{2.1.229} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.229.jar) 
	UCH	BiomesOPlenty{5.0.0.2093} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2093-universal.jar) 
	UCH	blockdrops{1.0.11} [Block Drops] (BlockDrops-1.10.2-1.0.11.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCH	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCH	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCH	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCH	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCH	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCH	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCH	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCH	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCH	IC2{2.6.87-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.87-ex110.jar) 
	UCH	forestry{5.2.16.321} [Forestry] (forestry_1.10.2-5.2.16.321.jar) 
	UCH	ElecCore{1.6.328} [ElecCore] (ElecCore-1.10.2-1.6.328.jar) 
	UCH	deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
	UCH	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.126_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.126_beta.jar) 
	UCH	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCE	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.4.jar) 
	UCE	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCH	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCH	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCH	HardcoreQuesting{1.10.2-5.0.0beta4} [Hardcore Questing Mode] (HQM-New Heights-1.10.2-5.0.0beta4.jar) 
	UCH	igi|bloodmagicintegration{1.1} [InGameInfoXML Blood Magic Integration] (IGI-BloodMagic-1.1.jar) 
	UCH	IGI|DeepResonanceIntegration{1.0} [InGameInfo-XML Deep Resonance Integration] (IGI-DeepResonance-1.0.jar) 
	UCH	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCH	InGameInfoXML{2.8.1.89} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.89-universal.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UCH	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCH	jeresources{0.5.4.68} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.68.jar) 
	UCH	lonelybiome{1.0} [Lonely Biome] (lonelybiome-1.9.4-1.0.jar) 
	UCH	lycanitesmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	arcticmobs{1.15.1.4 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	demonmobs{1.15.1.4 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	desertmobs{1.15.1.4 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	forestmobs{1.15.1.4 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	freshwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	infernomobs{1.15.1.4 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	junglemobs{1.15.1.4 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	mountainmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	plainsmobs{1.15.1.4 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	saltwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	shadowmobs{1.15.1.4 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	swampmobs{1.15.1.4 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCH	menumobs{1.10.3} [Menu Mobs] (MenuMobs-1.10.2-1.10.3.jar) 
	UCH	mtrm{1.2.1.19} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.19.jar) 
	UCH	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCH	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCH	mputils{1.2.0} [ModPack Utilities] (mputils-1.10.2-1.2.0.jar) 
	UCH	mpbasic{1.1.0} [ModPack Basic Tools] (mpbasic-1.10.2-1.1.0.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	StorageDrawers{1.10.2-3.4.2} [Storage Drawers] (StorageDrawers-1.10.2-3.4.2.jar) 
	UCH	refinedstorage{1.2.3} [Refined Storage] (refinedstorage-1.2.3.jar) 
	UCH	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCH	shadowmc{3.4.9} [ShadowMC] (ShadowMC-1.10.2-3.4.9.jar) 
	UCH	sis{0.1} [SimpleInventoryStarter] (SimpleInventoryStarter-0.1.jar) 
	UCH	SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
	UCH	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCH	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.214.jar) 
	UCH	wawla{2.3.1.214} [What Are We Looking At] (Wawla-1.10.2-2.3.1.214.jar) 
	UD	BiomeTweakerCore{2.1.229} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.229.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.87-ex110.jar)
  
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Don/Documents/Curse/Minecraft/Instances/Apocalyptic%20(1)/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
```

**Comment by LatvianModder** [comment]
Update latest forge
