### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by blarghhh** [LatvianModder/FTBUtilities#280]
I transferred my world to another computer and moved the save file via simple copy paste. But now I'm suffering from the auto backup and manual backup not running.

This is the error it's giving me.

[16:27:07] [Server thread/INFO]: [me] launched a manual backup!
[16:27:07] [Client thread/INFO]: [CHAT] [Server: Saved the world]
[16:27:07] [Client thread/INFO]: [CHAT] [me] launched a manual backup!
[16:27:07] [Thread-87/INFO] [FTBU Backups]: Backing up 176 files...
[16:27:07] [Thread-87/INFO]: Failed to save world! (java.io.FileNotFoundException)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: .\backups\2016-11-28-16-27-07\backup.zip (The process cannot access the file because it is being used by another process)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.open(Native Method)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ftb.utils.world.ThreadBackup.doBackup(ThreadBackup.java:58)
[16:27:07] [Thread-87/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ftb.utils.world.ThreadBackup.run(ThreadBackup.java:27)
[16:27:07] [Server thread/INFO]: Turned on world auto-saving
[16:27:07] [Client thread/INFO]: [CHAT] Failed to save world! (java.io.FileNotFoundException)
[16:27:07] [Client thread/INFO]: [CHAT] [Server: Turned on world auto-saving]

I'm playing Infinity Skyblock with the curse client. 

FTBUtilities-1.7.10-1.0.18.3 is the version I'm using.

**Comment by LatvianModder** [comment]
This has never happened before. It says the file is being used by some other program, are you sure it isn't open somwhere else, like in a .zip archiver? Maybe restarting the computer might fix this

**Comment by blarghhh** [comment]
i can confirm that. the steps i took to try and fix it.

1. copied the entire save folder to the HDD that the modpack is installed in ie. FTB Infinity Skyblock for the curse client
2. restarted the PC and same issue
3. run curse client as admin, same issue

**Comment by blarghhh** [comment]
question,

is there a cooldown on the backup? cause sometimes the auto backup doesn't work when i set it to 30 minutes but works constantly if i set to every hour.

**Comment by LatvianModder** [comment]
It might be taking 0.x as 0, so maybe its best to set it to 1 and leave it that way. If there is a bug in 1.7.10, I wont fix it anyway, since 1.7.10 is no longer supported

**Comment by blarghhh** [comment]
okay then.

**Comment by thelapisfox** [comment]
This bug is occurring in 1.12.2 for me. Same exact error and restarting does not fix it. This is on the Stoneblock 2 mod pack.

**Comment by Tahakk** [comment]
@thelapisfox create a new issue with complete informations please, this one is 4 years old
