### ISSUE TITLE
sponge forge

### ISSUE THREAD

**Issue by Sitherious** [LatvianModder/FTBUtilities#313]
still crashes using #292

[00:36:47] [Server thread/INFO]: Starting minecraft server version 1.10.2
[00:37:54] [Server thread/INFO]: Loading properties
[00:37:54] [Server thread/WARN]: resource-pack-hash is deprecated and found along side resource-pack-sha1. resource-pack-hash will be ignored.
[00:37:54] [Server thread/INFO]: Default game type: SURVIVAL
[00:37:54] [Server thread/INFO]: Generating keypair
[00:37:54] [Server thread/INFO]: Starting Minecraft server on 62.210.102.231:26017
[00:37:54] [Server thread/INFO]: Using epoll channel type
[00:37:55] [pool-2-thread-3/INFO]: The lottery pot is empty, the draw is postponed!
[00:37:55] [pool-2-thread-4/INFO]: Current pot is at 0.0C! Use /lottery buy [amount] to buy tickets!
[00:38:15] [Server thread/INFO]: Preparing level "RTG"
[00:38:17] [Server thread/WARN]: Couldn't find resource table railcraft:chests/village_workshop
[00:38:17] [Server thread/INFO]: Preparing start region for level 0 (RTG)
[00:38:18] [Server thread/INFO]: Preparing spawn area: 10%
[00:38:19] [Server thread/INFO]: Preparing spawn area: 43%
[00:38:20] [Server thread/INFO]: Preparing spawn area: 88%
[00:38:21] [Server thread/INFO]: Preparing start region for level 0 (RTG)
[00:38:21] [Server thread/INFO]: Done (6.287s)! For help, type "help" or "?"
[00:38:24] [Server thread/INFO]: FTBLib: Server reloaded in 33ms
[00:38:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)

Caused by: java.lang.IllegalArgumentException: A plugin may not register multiple commands for the same alias ('rftdb')!
	at org.spongepowered.common.command.SpongeCommandManager.register(SpongeCommandManager.java:147) ~[SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2008]
	at org.spongepowered.common.command.SpongeCommandManager.register(SpongeCommandManager.java:122) ~[SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2008]
	at net.minecraft.command.ServerCommandManager.func_71560_a(SourceFile:108) ~[bd.class:?]
	at com.feed_the_beast.ftbu.FTBU.serverStarted(FTBU.java:100) ~[FTBU.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[custom.jar:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:52) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:858) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[00:38:24] [Server thread/ERROR]: This crash report has been saved to: /home/theminecrafthosting/multicraft/servers/server426/./crash-reports/crash-2016-12-28_00.38.24-server.txt
[00:38:24] [Server thread/INFO]: Stopping server
[00:38:24] [Server thread/INFO]: Saving players
[00:38:24] [Server thread/INFO]: Saving worlds
[00:38:25] [Server Shutdown Thread/INFO]: Stopping server

**Comment by Sitherious** [comment]
issue is fixed with the new sponge.
