### ISSUE TITLE
Wrench from Tech Reborn Crash due to Rank Check

### ISSUE THREAD

**Issue by votex09** [LatvianModder/FTBUtilities#362]
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.feed_the_beast.ftbl.lib.util.LMServerUtils.isOP(LMServerUtils.java:212)
	at com.feed_the_beast.ftbu.ranks.Ranks.getRank(Ranks.java:74)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.getRank(FTBUtilitiesAPI_Impl.java:55)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.hasPermission(FTBUtilitiesAPI_Impl.java:73)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at techreborn.items.tools.ItemWrench.onItemUseFirst(ItemWrench.java:53)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:399)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.redirect$onRightClickMouse$zzj000(Minecraft.java:146)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Caused by: Using the wrench on any block from Tech Reborn that is wrench compatible.

**Comment by LatvianModder** [comment]
This will be fixed in either next TechReborn release or FTBLib release (TR might be faster), I already spoke with dev :)

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+
