### ISSUE TITLE
[1.10.2] Client Crash opening TeamGUI

### ISSUE THREAD

**Issue by oryfoxer7410** [LatvianModder/FTBUtilities#378]
// Don't do that.

Time: 3/10/17 9:57 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.feed_the_beast.ftbl.client.teamsgui.GuiMyTeam$2.addWidgets(GuiMyTeam.java:155)
	at com.feed_the_beast.ftbl.lib.gui.PanelLM.refreshWidgets(PanelLM.java:48)
	at com.feed_the_beast.ftbl.api.gui.IPanel.add(IPanel.java:22)
	at com.feed_the_beast.ftbl.client.teamsgui.GuiMyTeam.addWidgets(GuiMyTeam.java:433)
	at com.feed_the_beast.ftbl.lib.gui.PanelLM.refreshWidgets(PanelLM.java:48)
	at com.feed_the_beast.ftbl.lib.gui.GuiLM.updateGui(GuiLM.java:145)
	at com.feed_the_beast.ftbl.lib.gui.GuiWrapper.func_73863_a(GuiWrapper.java:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.feed_the_beast.ftbl.client.teamsgui.GuiMyTeam$2.addWidgets(GuiMyTeam.java:155)
	at com.feed_the_beast.ftbl.lib.gui.PanelLM.refreshWidgets(PanelLM.java:48)
	at com.feed_the_beast.ftbl.api.gui.IPanel.add(IPanel.java:22)
	at com.feed_the_beast.ftbl.client.teamsgui.GuiMyTeam.addWidgets(GuiMyTeam.java:433)
	at com.feed_the_beast.ftbl.lib.gui.PanelLM.refreshWidgets(PanelLM.java:48)
	at com.feed_the_beast.ftbl.lib.gui.GuiLM.updateGui(GuiLM.java:145)
	at com.feed_the_beast.ftbl.lib.gui.GuiWrapper.func_73863_a(GuiWrapper.java:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: com.feed_the_beast.ftbl.lib.gui.GuiWrapper
	Mouse location: Scaled: (16, 12). Absolute: (33, 874)
	Screen size: Scaled: (2400, 450). Absolute: (4800, 900). Scale factor of 2

**Comment by ThomasAunvik** [comment]
FTBUtils and FTBLib Version? And please use pastebin to post the crash log, and a full crash log.

**Comment by LatvianModder** [comment]
No this was enough. I may have fixed this? I dont remember what specific changes I made, I know what the cause was tho
