### ISSUE TITLE
[1.10.2] Badge NullPointerException

### ISSUE THREAD

**Issue by Hodel1** [LatvianModder/FTBUtilities#427]
I got a error message, when a player does join the server.
Nobody can do any action on this world. (example block breaking)

Tested in FTB Beyond 1.5.3 with SpongeForge, forgeguard, custom multiworld plugin and nucleus.

[15:44:49] [Badge_687a7c78-067b-48ab-80fc-97a4f7bc31df/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[15:44:49] [Badge_687a7c78-067b-48ab-80fc-97a4f7bc31df/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.world.FTBUPlayerData.get(FTBUPlayerData.java:49)
[15:44:49] [Badge_687a7c78-067b-48ab-80fc-97a4f7bc31df/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.world.FTBUUniverseData.getBadge(FTBUUniverseData.java:111)
[15:44:49] [Badge_687a7c78-067b-48ab-80fc-97a4f7bc31df/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.net.MessageRequestBadge$ThreadBadge.run(MessageRequestBadge.java:32)
[15:44:49] [Badge_c6681bb2-01d2-4cac-b458-2450bb605502/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[15:44:49] [Badge_c6681bb2-01d2-4cac-b458-2450bb605502/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.world.FTBUPlayerData.get(FTBUPlayerData.java:49)
[15:44:49] [Badge_c6681bb2-01d2-4cac-b458-2450bb605502/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.world.FTBUUniverseData.getBadge(FTBUUniverseData.java:111)
[15:44:49] [Badge_c6681bb2-01d2-4cac-b458-2450bb605502/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at com.feed_the_beast.ftbu.net.MessageRequestBadge$ThreadBadge.run(MessageRequestBadge.java:32)

**Comment by LatvianModder** [comment]
That should be fixed now
