### ISSUE TITLE
FTBU 1.1x-3.6.0 for 1.11.2 crashes: NoSuchMethodError

### ISSUE THREAD

**Issue by Partonetrain** [LatvianModder/FTBUtilities#447]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  literalascension (literalascension-1.11.2-1.0.2.0.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 5/7/17 11:20 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_150895_a(Lnet/minecraft/item/Item;Lnet/minecraft/creativetab/CreativeTabs;Ljava/util/List;)V
	at com.feed_the_beast.ftbl.lib.client.DrawableObjectList.<init>(DrawableObjectList.java:59)
	at com.feed_the_beast.ftbu.integration.TiCIntegration.onGuideEvent(TiCIntegration.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_125_TiCIntegration_onGuideEvent_ClientGuideEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at com.feed_the_beast.ftbu.gui.Guides.func_110549_a(Guides.java:171)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at com.feed_the_beast.ftbu.client.FTBUClient.postInit(FTBUClient.java:45)
	at com.feed_the_beast.ftbu.FTBU.onPostInit(FTBU.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177671464 bytes (169 MB) / 1744306176 bytes (1663 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJ	forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJ	jei{4.3.4.273} [Just Enough Items] (jei_1.11.2-4.3.4.273.jar) 
	UCHIJ	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJ	arche{1.11.2-1.2.1} [Arche] (arche-1.11.2-1.2.1.jar) 
	UCHIJ	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCHIJ	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	UCHIJ	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJ	computercraft{1.81} [Computality] (computality-1.81.jar) 
	UCHIJ	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(17mar17).jar) 
	UCHIJ	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.1.jar) 
	UCHIE	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.0.jar) 
	UCHIJ	silentlib{2.1.2} [Silent Lib] (SilentLib-1.11.x-2.1.2-57.jar) 
	UCHIJ	funores{1.5.2} [Fun Ores] (FunOres-1.11.x-1.5.2c-107.jar) 
	UCHIJ	gardenofglass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHIJ	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJ	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCHIJ	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
	UCHIJ	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJ	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJ	literalascension{1.11.2-1.0.2.0} [Literal Ascension] (literalascension-1.11.2-1.0.2.0.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	pillar{1.0.0} [Corail Pillar] (pillar-1.0.0-1.11.2.jar) 
	UCHIJ	simplecorn{2.1.5} [Simple Corn] (SimpleCorn1.11.2-2.1.5.jar) 
	UCHIJ	snad{1.11.2-1.7.03.26a} [Snad] (Snad-1.11.2-1.7.03.26a.jar) 
	UCHIJ	tconstruct{1.11.2-2.7.0.12} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.12.jar) 
	UCHIJ	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJ	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJ	wanionlib{1.11.2-1.0} [WanionLib] (WanionLib-1.11.2-1.0.jar) 
	UCHIJ	yabba{1.11.2-0.5.0} [YABBA] (YABBA-1.11.2-0.5.0.jar) 
	UCHIJ	unidict{1.11.2-1.0} [UniDict] (UniDict-1.11.2-1.0.jar) 
	Loaded coremods (and transformers): 
literalascension (literalascension-1.11.2-1.0.2.0.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.4.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by LatvianModder** [comment]
Update FTBU and FTBL to 3.6.3
