### ISSUE TITLE
Mods don't work server-side-only

### ISSUE THREAD

**Issue by Schaefer78** [LatvianModder/FTBUtilities#502]
Is there a way to run FTBu server side only? Been waiting for another mod to use permissions on my forge Vanilla MC server but experimenting in the mean time trying to get something to work. Other mods just suck but FTBu Ranks and FE (which seems to not getting updated).

Has anyone have any thoughts on this if its possible. Thanks

**Comment by boazcstrike** [comment]
Hi, I run FTBu server side only, and it seems to work fine without any mods.
On another topic, I tried installing a bunch of mods like Minecolonies, Immersive Engineering, etc. and it broke the game. Forever having an eating animation without actually eating the food.

But yeah, you can place it on the server-side only.

**Comment by Schaefer78** [comment]
I've tested this now on my forge VMC server and the Vanilla client will not connect, forge client no mod won't as well,,, BUT a forge client running the FTBu will. Looks like im stuck in Permissions limbo since mods like Thut and others just suck and unstable.

**Comment by LatvianModder** [comment]
You can't use Thut or Sponge or Forge Essentials together with FTBUtilities.. or one with another, for that matter, not properlry at least. You should be able to just throw in FTBU and FTBL on server side without clients, it should work. If it doesnt, show me your client and server logs

**Comment by Schaefer78** [comment]
This is just FTBu and FTBL installed and when a client with no mods installed connects i see this in the logs.

> [21:18:03] [Server thread/INFO] [FML]: Connection received without FML marker, assuming vanilla.
> [21:18:03] [Server thread/INFO] [FML]: [Server thread] Server side vanilla connection established
> [21:18:03] [Server thread/INFO]: user/ip logged in with entity id 161 at (-1239.5, 113.0, -9478.5)
> [21:18:03] [Server thread/INFO]: userjoined joined the game
> [21:18:03] [Server thread/INFO] [FML]: Opening channel which already seems to have a state set. This is a vanilla connection. Handshake handler will stop now
> [21:18:06] [Server thread/INFO]: userleaving lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
> [21:18:06] [Server thread/INFO]: userleft left the game

this is the sever mod dir.
[.... data]# ll mods
 Jul  7 21:35 FTBLib-4.0.5.jar
 Jul  6 17:40 FTBUtilities-4.0.3.jar
 Aug  4 17:14 mod_list.json

Any advise?

**Comment by LatvianModder** [comment]
This probably shouldnt happen, gonna mark that as bug

**Comment by LatvianModder** [comment]
Does it still happen with latest versions?

**Comment by Schaefer78** [comment]
I will check and get back to u.

**Comment by Schaefer78** [comment]
When only ftbu and ftbLibs installed server will not start remove them server starts.

[07:22:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[07:22:06] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[07:22:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[07:22:07] [main/INFO] [FML]: Forge Mod Loader version 14.23.0.2494 for Minecraft 1.12.2 loading
[07:22:07] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:2.6.32-431.29.2.el6.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre
[07:22:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:22:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[07:22:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:22:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:22:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:22:09] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[07:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[07:22:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[07:22:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[07:22:10] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[07:22:16] [Server thread/INFO]: Starting minecraft server version 1.12.2
[07:22:16] [Server thread/INFO] [FML]: MinecraftForge v14.23.0.2494 Initialized
[07:22:17] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[07:22:17] [Server thread/INFO] [FML]: Replaced 1036 ore ingredients
[07:22:17] [Server thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[07:22:17] [Server thread/INFO] [FML]: Searching /home/schempire/mods for mods
[07:22:18] [Server thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[07:22:18] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[07:22:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, ftbl, ftbu] at CLIENT
[07:22:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, ftbl, ftbu] at SERVER
[07:22:20] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[07:22:20] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[07:22:20] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[07:22:20] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[07:22:20] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[07:22:20] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[07:22:20] [Server thread/INFO] [FTBLib]: Loading FTBLib, DevEnv:false
[07:22:20] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: AHEAD Target: null
[07:22:21] [Server thread/WARN] [FML]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with com.feed_the_beast.ftbu.ranks.FTBUPermissionHandler
[07:22:21] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:21] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:21] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:21] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:21] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:21] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:21] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:21] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:21] [Server thread/INFO] [FML]: Injecting itemstacks
[07:22:21] [Server thread/INFO] [FML]: Itemstack injection complete
[07:22:21] [Server thread/INFO]: Loading properties
[07:22:21] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[07:22:21] [Server thread/INFO]: Default game type: SURVIVAL
[07:22:21] [Server thread/INFO]: Generating keypair
[07:22:21] [Server thread/INFO]: Starting Minecraft server on *:25565
[07:22:21] [Server thread/INFO]: Using epoll channel type
[07:22:21] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:21] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:21] [Server thread/INFO] [FML]: Injecting itemstacks
[07:22:21] [Server thread/INFO] [FML]: Itemstack injection complete
[07:22:22] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[07:22:22] [Server thread/INFO]: Preparing level "world"
[07:22:22] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[07:22:22] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:22] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:22] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@3acc5e25)
[07:22:23] [Server thread/INFO]: Loaded 489 advancements
[07:22:23] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@3acc5e25)
[07:22:23] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@3acc5e25)
[07:22:23] [Server thread/INFO] [FTBUtilities]: Loading ranks..
[07:22:23] [Server thread/INFO] [FTBLib]: Reloaded server in 97ms
[07:22:23] [Server thread/INFO]: Preparing start region for level 0
[07:22:24] [Server thread/INFO]: Preparing spawn area: 0%
[07:22:25] [Server thread/INFO]: Preparing spawn area: 46%
[07:22:26] [Server thread/INFO]: Done (4.350s)! For help, type "help" or "?"
[07:22:26] [Server thread/FATAL] [FML]: Fatal errors were detected during the transition from SERVER_STARTING to SERVER_STARTED. Loading cannot continue
[07:22:26] [Server thread/FATAL] [FML]:
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State     | ID        | Version      | Source                                  | Signature                                |
        |:--------- |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
        | UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
        | UCHIJAAAA | mcp       | 9.42         | minecraft.jar                           | None                                     |
        | UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.0.2494-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | forge     | 14.23.0.2494 | forge-1.12.2-14.23.0.2494-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | ftbl      | 4.1.6        | FTBLib-4.1.6.jar                        | None                                     |
        | UCHIJAAAE | ftbu      | 4.1.6        | FTBUtilities-4.1.6.jar                  | None                                     |

[07:22:26] [Server thread/FATAL] [FML]: The following problems were captured during this phase
[07:22:26] [Server thread/ERROR] [FML]: Caught exception from ftbu (java.lang.NumberFormatException: For input string: "48H")
[07:22:26] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)

Caused by: java.lang.NumberFormatException: For input string: "48H"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_111]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_111]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_111]
        at com.feed_the_beast.ftbu.util.backups.Backups.init(Backups.java:78) ~[Backups.class:?]
        at com.feed_the_beast.ftbu.FTBU.onServerStarted(FTBU.java:59) ~[FTBU.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611) ~[forge-1.12.2-14.23.0.2494-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[forge-1.12.2-14.23.0.2494-universal.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[forge-1.12.2-14.23.0.2494-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:844) ~[Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:300) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[07:22:26] [Server thread/ERROR]: This crash report has been saved to: /home/schempire/./crash-reports/crash-2017-10-01_07.22.26-server.txt
[07:22:26] [Server thread/INFO]: Stopping server
[07:22:26] [Server thread/INFO]: Saving players
[07:22:26] [Server thread/INFO]: Saving worlds
[07:22:26] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[07:22:26] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[07:22:26] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[07:22:26] [Server thread/INFO] [FML]: Unloading dimension 0
[07:22:26] [Server thread/INFO] [FML]: Unloading dimension -1
[07:22:26] [Server thread/INFO] [FML]: Unloading dimension 1
[07:22:27] [Server thread/INFO] [FML]: Applying holder lookups
[07:22:27] [Server thread/INFO] [FML]: Holder lookups applied
[07:22:27] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[07:22:27] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[07:22:27] [Server Shutdown Thread/INFO]: Stopping server
[07:22:27] [Server Shutdown Thread/INFO]: Saving players
[07:22:27] [Server Shutdown Thread/INFO]: Saving worlds

**Comment by LatvianModder** [comment]
That's unrelated issue - you have 48H. See comment on backups for proper backup time formatting, it's HH:MM without letters

**Comment by Schaefer78** [comment]
Oh ill look into that and get back to u.

**Comment by Schaefer78** [comment]
Awesome Sir!

I had to remove all my old backups in the backup dir but after doing so FTBu and FTBLibs work with server side only and a vmc client can now join!

Thank you so much for fixing this. Cannot wait to fully get this implemented in my community's VMC experience.
