### ISSUE TITLE
couldn't procces command

### ISSUE THREAD

**Issue by deviraux** [LatvianModder/FTBUtilities#575]
No Idea why this happened but after a reboot on my server everyone lost access to all the gui functions in ftbu version 1.1x-3.6.5

: Couldn't process command: 'ftb team gui'
java.lang.NullPointerException
        at com.feed_the_beast.ftbl.api_impl.ForgeTeam.getHighestStatus(ForgeTeam.java:363) ~[ForgeTeam.class:?]
        at com.feed_the_beast.ftbl.api_impl.ForgeTeam.hasStatus(ForgeTeam.java:422) ~[ForgeTeam.class:?]
        at com.feed_the_beast.ftbl.api.IForgeTeam.hasStatus(IForgeTeam.java:44) ~[IForgeTeam.class:?]
        at com.feed_the_beast.ftbl.net.MessageSelectTeamGui.<init>(MessageSelectTeamGui.java:31) ~[MessageSelectTeamGui.class:?]
        at com.feed_the_beast.ftbl.cmd.team.CmdGui.func_184881_a(CmdGui.java:87) ~[CmdGui.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]
        at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:147) ~[CommandTreeBase.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]
        at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:147) ~[CommandTreeBase.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[17:43:45] [Server thread/INFO]: Deviraux lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}

**Comment by LatvianModder** [comment]
Sorry, 1.11 is no longer supported. Looks like some player data broke, maybe you can restore `world/data` from older backup
