### ISSUE TITLE
Crash when loading guides (1.10.2)

### ISSUE THREAD

**Issue by HydrogenC** [LatvianModder/FTBUtilities#616]
Crash report here, it crashes during the phase "finishing up-guides".

Report here: 
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  RefinedFixerLoadingPlugin (ImmersiveCables-1.10.2-1.2.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  BetterFontsCore (TTFR-1.10.2-1.5.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/26/18 8:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/tools/ItemStackTools
	at com.feed_the_beast.ftbl.lib.client.ImageProvider.get(ImageProvider.java:89)
	at com.feed_the_beast.ftbl.lib.client.ImageProvider.get(ImageProvider.java:80)
	at com.feed_the_beast.ftbl.lib.client.ImageProvider.get(ImageProvider.java:75)
	at com.feed_the_beast.ftbu.gui.Guides.loadTree(Guides.java:264)
	at com.feed_the_beast.ftbu.gui.Guides.func_110549_a(Guides.java:146)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at com.feed_the_beast.ftbu.client.FTBUClient.postInit(FTBUClient.java:45)
	at com.feed_the_beast.ftbu.FTBU.onPostInit(FTBU.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mcjty.lib.tools.ItemStackTools
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more

**Comment by LatvianModder** [comment]
Install CompatLayer mod
