### ISSUE TITLE
Crash on Pre Initialization to Initialization

### ISSUE THREAD

**Issue by MeruC** [LatvianModder/FTBUtilities#623]
I tried using the latest and other versions but still crashing.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed (1).jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.4-anarchy.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (Quark-r1.1-70 (1).jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26 (1).jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/2/18 1:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBLib (ftbl)
Caused by: java.lang.NoClassDefFoundError: com/feed_the_beast/ftbl/api/events/LoadWorldDataEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:83)
	at com.feed_the_beast.ftbu.FTBLibIntegration.init(FTBLibIntegration.java:55)
	at com.feed_the_beast.ftbl.api_impl.FTBLibAPI_Impl.init(FTBLibAPI_Impl.java:70)
	at com.feed_the_beast.ftbl.FTBLibMod.onPreInit(FTBLibMod.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.feed_the_beast.ftbl.api.events.LoadWorldDataEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 85277704 bytes (81 MB) / 380223488 bytes (362 MB) up to 1593180160 bytes (1519 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1536M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_E7 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	additionalresources{0.1.1} [Additional Resources] (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed (1).jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCH	aether_legacy{1.10.2-v1.6} [Aether Legacy] (aether_legacy-1.10.2-v1.6.jar) 
	UCH	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13 (1).jar) 
	UCH	Botania{r1.9-341} [Botania] (Botania+r1.9-341.jar) 
	UCH	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCH	audiodeath{0.6.4_1.9-72ff444} [Audio Death] (audiodeath-1.9-0.6.4.49+72ff444 (1).jar) 
	UCH	Psi{r1.0-42} [Psi] (Psi-r1.0-42 (1).jar) 
	UCH	Quark{r1.1-70} [Quark] (Quark-r1.1-70 (1).jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2 (1).jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCH	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0 (1).jar) 
	UCH	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26 (1).jar) 
	UCH	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39 (1).jar) 
	UCH	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420 (1).jar) 
	UCH	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal (1).jar) 
	UCH	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCH	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCH	CodeChickenCore{2.4.1.103} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.103-universal.jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26 (1).jar) 
	UCH	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26 (1).jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26 (1).jar) 
	UCH	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5 (1).jar) 
	UCH	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCH	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcake-1.9.4-0.0.1.jar) 
	UCH	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.3.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.4-anarchy.jar) 
	UCH	forgelin{1.6.0} [Shadowfacts' Forgelin] (Forgelin-1.6.0.jar) 
	UCE	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCE	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.3.jar) 
	UCH	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.10.2-alpha-0.0.3.jar) 
	UCH	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCH	theoneprobe{1.4.19} [The One Probe] (theoneprobe-1.1x-1.4.19.jar) 
	UCH	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61 (1).jar) 
	UCH	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCH	librarianlib{1.10.1} [LibrarianLib] (librarianlib-1.10.1.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-1.0.3 (1).jar) 
	UCH	modtweaker{2.0.13} [Mod Tweaker] (ModTweaker2-2.0.13.jar) 
	UCH	mxtune{0.4.0-dev.25} [mxTune] (mxtune-1.10.2-0.4.0-dev.25.jar) 
	UCH	ProjectE{1.10.2-PE1.3.1} [ProjectE] (ProjectE-1.10.2-PE1.3.1.jar) 
	UCH	refraction{1.3.4} [Refraction] (refraction-1.3.4.jar) 
	UCH	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCH	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCH	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCH	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10 (1).jar) 
	UCH	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCH	torchmaster{1.4.1.34} [TorchMaster] (torchmaster_1.10.2-1.4.1.34.jar) 
	UCH	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	UCH	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCH	VeinMiner{0.38.1_1.9-5587fc8} [Vein Miner] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	UCH	VeinMinerModSupport{0.38.1_1.9-5587fc8} [Mod Support] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	UCH	villagebox{0.6.0} [Village Box] (villagebox-1.10.2-0.6.0.jar) 
	UCH	voidislandcontrol{1.1.7} [Void Island Control] (voidislandcontrol-1.1.7.jar) 
	UCH	librarianliblate{1.10.1} [LibrarianLib Stage 2] (librarianlib-1.10.1.jar) 
	Loaded coremods (and transformers): 
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed (1).jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.4-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LoadingPlugin (Quark-r1.1-70 (1).jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26 (1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11399 Compatibility Profile Context' Renderer: 'AMD Radeon HD 6300 series Graphics'
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	OptiFine Version: OptiFine_1.10.2_HD_U_E7
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.11399 Compatibility Profile Context
	OpenGlRenderer: AMD Radeon HD 6300 series Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by LatvianModder** [comment]
You have outdated FTBLib
