### ISSUE TITLE
Synchronous writes from Universe.save (performance)

### ISSUE THREAD

**Issue by sfPlayer1** [LatvianModder/FTBUtilities#650]
com.feed_the_beast.ftblib.lib.data.Universe.save writes its data on the server thread, stalling until the rather slow disk I/O is complete. The data being written is tiny, but I/O completion still takes a long time depending on the involved hardware and system load.

Single-tick-span NPS showing the problem: http://files.player.to/tmp/spike-1863-1113213791_out.nps (~450 ms delay within 1 tick)

Suggested solution similar to https://gist.github.com/cpw/10938f8311c4b53dbd7e523f36b19770 - capture a data snapshot, then write using MC's I/O thread. More than one IThreadedFileIO instance per save should be avoided, otherwise it may interfere badly with the pending I/O queue.

It is also strongly advised to only save data that has changed, currently it seems to save unconditionally. The 350 ms toJson invocation from the NPS above just writes `{"world_id": "aaa9cc7540684aa49eadd1e4859d209c"}`, which is unlikely to not be a constant.

**Comment by LatvianModder** [comment]
Done. At least for most important things, like all universe/player/team data

**Comment by LatvianModder** [comment]
Can you verify that this is good now? cc @cpw https://github.com/LatvianModder/FTBLib/blob/de61380a4aa522666da3f0d65c9c5f639b41b39d/src/main/java/com/feed_the_beast/ftblib/lib/data/Universe.java?ts=4#L314-L423

**Comment by sfPlayer1** [comment]
Can't test, the FTBLib API is now incompatible with ftb achievements:

```
java.lang.IllegalAccessError: tried to access field com.feed_the_beast.ftblib.lib.data.ForgeTeam.title from class me.modmuss50.ftba.util.FTBTeamUtil
        at me.modmuss50.ftba.util.FTBTeamUtil.lambda$createTeams$1(FTBTeamUtil.java:80) ~[FTBTeamUtil.class:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_162]
        at me.modmuss50.ftba.util.FTBTeamUtil.createTeams(FTBTeamUtil.java:76) ~[FTBTeamUtil.class:?]
...
```

FYI the old code throwed on shutdown, likely a separate bug:
```
[16:51:29] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.data.Universe:lambda$onWorldSaved$0:327]: java.lang.NullPointerException
[16:51:29] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.data.Universe:lambda$onWorldSaved$0:327]:     at com.feed_the_beast.ftblib.lib.data.Universe.lambda$onWorldSaved$0(Universe.java:323)
[16:51:29] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.data.Universe:lambda$onWorldSaved$0:327]:     at net.minecraft.world.storage.ThreadedFileIOBase.processQueue(SourceFile:37)
[16:51:29] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.data.Universe:lambda$onWorldSaved$0:327]:     at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
[16:51:29] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.data.Universe:lambda$onWorldSaved$0:327]:     at java.lang.Thread.run(Thread.java:748)
```

**Comment by modmuss50** [comment]
Here is an updated FTB Achievements that should work with the latest FTB Lib:

https://minecraft.curseforge.com/projects/ftb-achievements/files/2537551

**Comment by sfPlayer1** [comment]
It looks like the issue is fixed from some quick measurements.
