### ISSUE TITLE
NullPointerException when serializing team data during world save

### ISSUE THREAD

**Issue by matracy** [LatvianModder/FTBUtilities#680]
[crash-2018-03-31_17.10.03-server.txt](https://github.com/LatvianModder/FTBUtilities/files/1868070/crash-2018-03-31_17.10.03-server.txt)
The first time I put the FTButils on the server, everything functioned as normal.  After I had changed some settings to for a few mods, I issued the stop command, and now every time I start the server, it crashes with the same set of errors (repeated six times).  Is there anything I can do to fix this?

**Comment by Ricket** [comment]
I hit the same, apparently triggered by AromaBackup trying to trigger a save:

```
[00:14:29] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Save@72abd9e5:
java.lang.NullPointerException: null
        at com.feed_the_beast.ftbutilities.data.FTBUTeamData.serializeNBT(FTBUTeamData.java:58) ~[FTBUTeamData.class:?]
        at com.feed_the_beast.ftbutilities.data.FTBUTeamData.serializeNBT(FTBUTeamData.java:27) ~[FTBUTeamData.class:?]
        at com.feed_the_beast.ftblib.lib.data.NBTDataStorage.serializeNBT(NBTDataStorage.java:79) ~[NBTDataStorage.class:?]
        at com.feed_the_beast.ftblib.lib.data.ForgeTeam.serializeNBT(ForgeTeam.java:128) ~[ForgeTeam.class:?]
        at com.feed_the_beast.ftblib.lib.data.Universe.save(Universe.java:374) ~[Universe.class:?]
        at com.feed_the_beast.ftblib.lib.data.Universe.onWorldSaved(Universe.java:106) ~[Universe.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_260_Universe_onWorldSaved_Save.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008) ~[oo.class:?]
        at aroma1997.backup.mc.ThreadBackup.saveLevel(ThreadBackup.java:205) ~[ThreadBackup.class:?]
        at aroma1997.backup.mc.ThreadBackup.lambda$makeBackup$0(ThreadBackup.java:129) ~[ThreadBackup.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at aroma1997.core.util.registry.TickRegistry$TickRegistrySingle.lambda$addSingleCallback$1(TickRegistry.java:167) ~[TickRegistry$TickRegistrySingle.class:?]
        at aroma1997.core.util.registry.TickRegistry$TickRegistrySingle.tick(TickRegistry.java:185) [TickRegistry$TickRegistrySingle.class:?]
        at aroma1997.core.util.registry.TickRegistry$3.serverTick(TickRegistry.java:66) [TickRegistry$3.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1695__serverTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

FTBUtilities-5.0.0.11.jar

**Comment by Ricket** [comment]
Looks like this commit fixed it, 7 days ago: https://github.com/LatvianModder/FTBUtilities/commit/d2ab6b4119a216226b21493272dcb0e1362fa266#diff-e6e63aba6c4ed580b2496b6044670123

Until a new version is released, it looks like you can fix it by (re)enabling chunk claiming in the config.

**Comment by matracy** [comment]
Thanks!  I was totally lost on this.  I will try what you said and see if it works.

**Comment by matracy** [comment]
It worked.  Thanks for the help!

**Comment by Ricket** [comment]
No problem, sorry you had to go a while without playing. Here's approximately the procedure I followed, so next time perhaps you can help yourself get going faster!

-----

Look at that first line of the stack trace to find the filename and line number:
        at com.feed_the_beast.ftbutilities.data.FTBUTeamData.serializeNBT(**FTBUTeamData.java:58**) ~[FTBUTeamData.class:?]

Go to the "FTBUTeamData.java" file, by:

1. Go to the mod's github main page, https://github.com/LatvianModder/FTBUtilities
2. Press T on your keyboard to open file finder.
3. Type the filename, hopefully it's just one result (or look for the one in like `src/main/java`), open it.

Look at the affected line (58) to see if you can glean any cause for the problem. Or, look at the history of the file to see if someone already fixed it (history button is in top right).

-----

(also I check in all my server config files into git, so I always know what changes I make or what a modpack update has actually updated -- I recommend this, with the caveat that you have to be very careful about your gitignore syntax)
