### ISSUE TITLE
SinglePlayer world crash.

### ISSUE THREAD

**Issue by Edwinchen1** [LatvianModder/FTBUtilities#730]
i have no issue open minecraft launcher and go to the world selection GUI,but when i enter a world(not matter what kind of world, whether i have played for some time or not), 100% crash guaranteed. 
Anyone have any idea? my guess is this mod only works for multiplayer world.
this mod works fire in the 1.10.2 minecraft single player world, but not 1.12.2.

**Comment by Edwinchen1** [comment]
also, this is the crash report.
[crash-2018-05-17_12.37.47-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2015243/crash-2018-05-17_12.37.47-server.txt)

**Comment by Edwinchen1** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 5/17/18 12:37 PM
Description: Exception in server tick loop

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/ITeleporter
	at com.feed_the_beast.ftblib.lib.util.ServerUtils.<clinit>(ServerUtils.java:49)
	at com.feed_the_beast.ftbutilities.ranks.Ranks.getRank(Ranks.java:98)
	at com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler.hasPermission(FTBUtilitiesPermissionHandler.java:62)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.hasPermission(ForgePlayer.java:364)
	at com.feed_the_beast.ftbutilities.data.FTBUtilitiesLoadedChunkManager.canForceChunks(FTBUtilitiesLoadedChunkManager.java:175)
	at com.feed_the_beast.ftbutilities.data.ClaimedChunks.update(ClaimedChunks.java:120)
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesWorldEventHandler.onServerTickEvent(FTBUtilitiesWorldEventHandler.java:75)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_108_FTBUtilitiesWorldEventHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/ITeleporter
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.ITeleporter
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4440558056 bytes (4234 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version                | Source                                           | Signature                                |
	|:--------- |:------------------------ |:---------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2                 | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                      | 9.42                   | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99              | forge-1.12.2-14.23.2.2611.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.2.2611           | forge-1.12.2-14.23.2.2611.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater        | 1.0                    | MercuriusUpdater-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2                  | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | jei                      | 4.9.1.168              | jei_1.12.2-4.9.1.168.jar                         | None                                     |
	| UCHIJAAAA | mantle                   | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCHIJAAAA | tweakersconstruct        | 1.12.2-1.2.0           | tweakersconstruct-1.12.2-1.2.0.jar               | None                                     |
	| UCHIJAAAA | tconstruct               | 1.12.2-2.9.1.65        | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCHIJAAAA | extrautils2              | 1.0                    | extrautils2-1.12-1.7.5.jar                       | None                                     |
	| UCHIJAAAA | flyringbaublemod         | 0.3.1_1.12-d4e654e     | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar      | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.1.6.339              | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | avaritia                 | 3.2.0                  | Avaritia-1.12-3.2.0.13-universal.jar             | None                                     |
	| UCHIJAAAA | avaritiatweaks           | 1.12.2-1.1             | AvaritiaTweaks-1.12.2-1.1.jar                    | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAA | base                     | 3.7.1                  | base-1.12.2-3.7.1.jar                            | None                                     |
	| UCHIJAAAA | battletowers             | 1.6.2                  | BattleTowers-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | betterbuilderswands      | 0.11.1                 | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  | None                                     |
	| UCHIJAAAA | bookshelf                | 2.3.537                | Bookshelf-1.12.2-2.3.537.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | redstoneflux             | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore             | 2.4.0                  | BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCHIJAAAA | clumps                   | 2.0.0                  | Clumps-3.0.0.jar                                 | None                                     |
	| UCHIJAAAA | cyclopscore              | 0.11.5                 | CyclopsCore-1.12.2-0.11.5.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | commoncapabilities       | 1.4.0                  | CommonCapabilities-1.12-1.4.0.jar                | None                                     |
	| UCHIJAAAA | cucumber                 | 1.1.0                  | cucumber-1.12-1.1.0.jar                          | None                                     |
	| UCHIJAAAA | darkutils                | 1.8.207                | DarkUtils-1.12.2-1.8.207.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | draconicevolution        | 2.3.10                 | Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCHIJAAAA | enderrift                | 2.1.9                  | EnderRift-1.12.1-2.1.9.jar                       | None                                     |
	| UCHIJAAAA | enderstorage             | 2.4.2.126              | EnderStorage-1.12.2-2.4.2.126-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | wanionlib                | 1.12.2-1.5             | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| UCHIJAAAA | eternalsingularity       | 1.12.2-.1.0.5          | eternalsingularity-1.12.2-1.0.5.jar              | None                                     |
	| UCHIJAAAA | exchangers               | 1.12.2-2.7.1           | Exchangers-1.12.2-2.7.1.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAA | mcmultipart              | 2.4.1                  | MCMultiPart-2.4.1.jar                            | None                                     |
	| UCHIJAAAA | sonarcore                | 5.0.9                  | sonarcore-1.12.2-5.0.9.jar                       | None                                     |
	| UCHIJAAAA | fluxnetworks             | 3.0.8                  | fluxnetworks-1.12.2-3.0.8.jar                    | None                                     |
	| UCHIJAAAA | ichunutil                | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
	| UCHIJAAAA | nei                      | 2.4.1                  | NotEnoughItems-1.12.2-2.4.1.233-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ftblib                   | 5.0.2.14               | FTBLib-5.0.2.14.jar                              | None                                     |
	| UCHIJAAAA | ftbutilities             | 5.0.2.14               | FTBUtilities-5.0.2.14.jar                        | None                                     |
	| UCHIJAAAA | infernalmobs             | 1.7.3                  | Infernal-Mobs-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | infinitefluids           | 1.2.0                  | infinitefluids-1.11-1.2.0.jar                    | None                                     |
	| UCHIJAAAA | integrateddynamics       | 0.11.10                | IntegratedDynamics-1.12.2-0.11.10.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | integrateddynamicscompat | 1.0.0                  | IntegratedDynamics-1.12.2-0.11.10.jar            | None                                     |
	| UCHIJAAAA | integratedtunnels        | 1.5.5                  | IntegratedTunnels-1.12.2-1.5.5.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | integratedtunnelscompat  | 1.0.0                  | IntegratedTunnels-1.12.2-1.5.5.jar               | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJAAAA | jeresources              | 0.8.5.27               | JustEnoughResources-1.12.2-0.8.5.27.jar          | None                                     |
	| UCHIJAAAA | llor                     | 1.1.4-mc1.12           | LLOverlayReloaded-1.1.4-mc1.12.jar               | None                                     |
	| UCHIJAAAA | mcjtylib_ng              | 2.6.7                  | mcjtylib-1.12-2.6.7.jar                          | None                                     |
	| UCHIJAAAA | meecreeps                | 1.1.0                  | meecreeps-1.12-1.1.0.jar                         | None                                     |
	| UCHIJAAAA | mob_grinding_utils       | 0.3.5                  | MobGrindingUtils-0.3.5.jar                       | None                                     |
	| UCHIJAAAA | mousetweaks              | 2.8                    | MouseTweaks-2.8-mc1.12.1.jar                     | None                                     |
	| UCHIJAAAA | mysticalagriculture      | 1.6.9                  | mysticalagriculture-1.12-1.6.9.jar               | None                                     |
	| UCHIJAAAA | mysticalagradditions     | 1.2.8                  | mysticalagradditions-1.12-1.2.8.jar              | None                                     |
	| UCHIJAAAA | notenoughwands           | 1.6.1                  | notenoughwands-1.12-1.6.1.jar                    | None                                     |
	| UCHIJAAAA | overloaded               | 0.0.52                 | Overloaded-1.12.2-0.0.52.jar                     | 644f38521a349310a5dae0239577dc7beebefaec |
	| UCHIJAAAA | peacefulsurface          | 1.12.2-v1              | PeacefulSurface-1.12.2-v1.jar                    | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | placebo                  | 1.3.2                  | Placebo-1.12.2-1.3.2.jar                         | None                                     |
	| UCHIJAAAA | potioncore               | 1.6_for_1.12.2         | PotionCore-1.6_for_1.12.2.jar                    | None                                     |
	| UCHIJAAAA | prefab                   | 1.3.0.18               | prefab-1.3.0.18.jar                              | None                                     |
	| UCHIJAAAA | projecte                 | 1.12-PE1.0.0           | ProjectE-1.12-PE1.2.0.jar                        | None                                     |
	| UCHIJAAAA | qualitytools             | 1.0.6_for_1.12.2       | QualityTools-1.0.6_for_1.12.2.jar                | None                                     |
	| UCHIJAAAA | refinedstorage           | 1.5.32                 | refinedstorage-1.5.32.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAAAA | refined_avaritia         | 2.0                    | refined_avaritia-1.12.2-2.0.jar                  | None                                     |
	| UCHIJAAAA | refinedstorageaddons     | 0.2                    | refinedstorageaddons-0.2.jar                     | None                                     |
	| UCHIJAAAA | rftools                  | 7.33                   | rftools-1.12-7.33.jar                            | None                                     |
	| UCHIJAAAA | rftoolspower             | 0.1.2                  | rftoolspower-1.12-0.1.2.jar                      | None                                     |
	| UCHIJAAAA | roguelike                | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| UCHIJAAAA | silentlib                | 2.2.18                 | SilentLib-1.12-2.2.18-100.jar                    | None                                     |
	| UCHIJAAAA | skyresources             | 2.2.3                  | skyresources-2.2.3.jar                           | None                                     |
	| UCHIJAAAA | sc                       | 1.2.2.1                | Sky+Compression-1.2.2.1.jar                      | None                                     |
	| UCHIJAAAA | yukarilib                | 1.3.0                  | YukariLib-1.12-1.3.0.jar                         | None                                     |
	| UCHIJAAAA | solidxp                  | 1.4.0-beta             | SolidXp-1.4.0-b2.jar                             | None                                     |
	| UCHIJAAAA | somanyenchantments       | 0.3.0                  | SoManyEnchantments+V0.3.1+(1.12.2).jar           | None                                     |
	| UCHIJAAAA | stacksize                | 1.1                    | stacksize-1.12.2-1.0.jar                         | None                                     |
	| UCHIJAAAA | theoneprobe              | 1.4.22                 | theoneprobe-1.12-1.4.22.jar                      | None                                     |
	| UCHIJAAAA | tinkersjei               | 1.0                    | tinkersjei-1.0.jar                               | None                                     |
	| UCHIJAAAA | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar                | None                                     |
	| UCHIJAAAA | torohealthmod            | 1.12.2-11              | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar      | None                                     |
	| UCHIJAAAA | uncrafted                | 3.0.1                  | Uncrafted+1.12++(v.3.0.1).jar                    | None                                     |
	| UCHIJAAAA | witherskelefix           | 2.5.0                  | Wither+Skeleton+Tweaks-1.12.2-2.5.0.jar          | None                                     |
	| UCHIJAAAA | xnet                     | 1.6.9                  | xnet-1.12-1.6.9.jar                              | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LatvianModder** [comment]
You need to update Forge version

**Comment by Edwinchen1** [comment]
what the f****? ok, let me have a try.

**Comment by Edwinchen1** [comment]
HOLY COW!! THAT WORKS!!
thank you very much.
really appreciate this.
