### ISSUE TITLE
[Bug]Server crash 

### ISSUE THREAD

**Issue by OldKingisdie** [LatvianModder/FTBUtilities#862]
forge ： 2705
mod version：
FTBUtilities-5.2.0.28
FTBLib-5.2.0.23

crash-report
```
[00:44:45] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityEvent$EnteringChunk@256a9805:
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayer.getTeam(EntityPlayer.java:2284) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDisplayName(EntityPlayer.java:2291) ~[aed.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getDisplayName(ForgePlayer.java:184) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgeTeam.getTitle(ForgeTeam.java:226) ~[ForgeTeam.class:?]
	at com.feed_the_beast.ftbutilities.FTBUtilitiesNotifications.updateChunkMessage(FTBUtilitiesNotifications.java:49) ~[FTBUtilitiesNotifications.class:?]
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler.onChunkChanged(FTBUtilitiesPlayerEventHandler.java:68) ~[FTBUtilitiesPlayerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_257_FTBUtilitiesPlayerEventHandler_onChunkChanged_EnteringChunk.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639) [EventBus.class:?]
	at net.minecraft.world.chunk.Chunk.addEntity(Chunk.java:739) [axw.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:3164) [oo.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:3149) [oo.class:?]
	at org.spongepowered.common.entity.EntityUtil.processEntitySpawn(EntityUtil.java:570) [EntityUtil.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.common.event.tracking.PhaseTracker.spawnEntityWithCause(PhaseTracker.java:960) [PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:3137) [oo.class:?]
	at net.minecraft.server.management.PlayerList.recreatePlayerEntity(PlayerList.java:1850) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClientStatus(NetHandlerPlayServer.java:1117) [pa.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:31) [lb.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:8) [lb.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlf000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[00:44:45] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[00:44:45] [Server thread/ERROR] [FML]: 0: HIGH
[00:44:45] [Server thread/ERROR] [FML]: 1: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler onChunkChanged(Lnet/minecraftforge/event/entity/EntityEvent$EnteringChunk;)V
[00:44:45] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[00:44:45] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_257_FTBUtilitiesPlayerEventHandler_onChunkChanged_EnteringChunk (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_257_FTBUtilitiesPlayerEventHandler_onChunkChanged_EnteringChunk)
[00:44:45] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.player.EntityPlayer.getTeam(EntityPlayer.java:2284) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDisplayName(EntityPlayer.java:2291) ~[aed.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getDisplayName(ForgePlayer.java:184) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgeTeam.getTitle(ForgeTeam.java:226) ~[ForgeTeam.class:?]
	at com.feed_the_beast.ftbutilities.FTBUtilitiesNotifications.updateChunkMessage(FTBUtilitiesNotifications.java:49) ~[FTBUtilitiesNotifications.class:?]
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler.onChunkChanged(FTBUtilitiesPlayerEventHandler.java:68) ~[FTBUtilitiesPlayerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_257_FTBUtilitiesPlayerEventHandler_onChunkChanged_EnteringChunk.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639) ~[EventBus.class:?]
	at net.minecraft.world.chunk.Chunk.addEntity(Chunk.java:739) ~[axw.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:3164) ~[oo.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:3149) ~[oo.class:?]
	at org.spongepowered.common.entity.EntityUtil.processEntitySpawn(EntityUtil.java:570) ~[EntityUtil.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.common.event.tracking.PhaseTracker.spawnEntityWithCause(PhaseTracker.java:960) ~[PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:3137) ~[oo.class:?]
	at net.minecraft.server.management.PlayerList.recreatePlayerEntity(PlayerList.java:1850) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClientStatus(NetHandlerPlayServer.java:1117) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:31) ~[lb.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:8) ~[lb.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlf000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 7 more
[00:44:45] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[00:44:45] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /42.186.61.150:44641
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zin000(NetHandlerPlayServer.java:2048) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.player.EntityPlayer.getTeam(EntityPlayer.java:2284) ~[aed.class:?]
	at net.minecraft.util.EntitySelectors.getTeamCollisionPredicate(SourceFile:91) ~[vk.class:?]
	at net.minecraft.entity.EntityLivingBase.collideWithNearbyEntities(EntityLivingBase.java:2430) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2387) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:513) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2170) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
	... 10 more
[00:44:45] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: chuxuan lost connection: Internal server error
[00:44:45] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayer.getTeam(EntityPlayer.java:2284) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDisplayName(EntityPlayer.java:2291) ~[aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:845) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.checkDisconnected(NetworkManager.java:453) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by OldKingisdie** [comment]
OK I found it maybe fix #796
